version: '3.9'

services:

  db:
    image: docker.io/library/postgres
    build:
      context: ..
    restart: always
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    ports:
      - "5432:5432"

  server:
    build:
      context: ..
      dockerfile: containers/server.Dockerfile
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgres://postgres:${PG_PASSWORD}@db:5432/postgres
