version: '3.9'

services:

  db:
    image: docker.io/library/postgres
    build:
      context: ..
    restart: always
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    ports:
      - "5432:5432"

